export const LOAD_INITIAL_DATA = 'LOAD_INITIAL_DATA'
export const LOAD_SSR_INITIAL_DATA = 'LOAD_SSR_INITIAL_DATA'
export const SELECT_LOCATION = 'SELECT_LOCATION'
export const SAVE_USER_CITY = 'SAVE_USER_CITY'